services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount local project directory to /app in the container
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    depends_on:
      - db
      - redis
      - elasticsearch
    env_file: 
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-local
      - cluster.max_shards_per_node=3000
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Dlog4j2.disable.jmx=true -Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      core:
        soft: 99999999
        hard: 99999999
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  postgres: {}
  elasticsearch: {}
